# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":hoje:"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d %b %Y"

  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # And much more! For more information, visit the docs: https://espanso.org/docs/

  # Pessoal
  - trigger: ":email:"
    replace: "rodrigues.am@usp.br"

  - trigger: ":amr:"
    replace: "André Machado Rodrigues"

  - trigger: ":assin:"
    replace: "-- \nProf. Dr. André Machado Rodrigues \nDepartamento de Física Aplicada \nInstituto de Física - Universidade de São Paulo \nTelefone: +55 (11) 3091-7108 \nSala: 3016 - Prédio Ala II"

  - trigger: ":cpf:"
    replace: "303.022.058-37"

  - trigger: ":nusp:"
    replace: "3560046"

  - trigger: ":dogn:"
    replace: "Chewbacca"

    # Trabalho
  - trigger: ":cocl:"
    replace: "CoC-Licenciatura"

  - trigger: ":cocfull:"
    replace: "Comissão Coordenadora do Curso de Licenciatura em Física"

  - trigger: ":coc:"
    replace: "Comissão Coordenadora do Curso"

  - trigger: ":ifusp:"
    replace: "Instituto de Física da Universidade de São Paulo"

  - trigger: ":piec:"
    replace: "Programa de Pós-Graduação Interunidades em Ensino de Ciências"

  - trigger: ":pibid:"
    replace: "Programa Institucional de Bolsas de Iniciação à Docência (Pibid)"

  - trigger: ":eevr:"
    replace: "E.E. Virgilia Rodrigues Alves de Carvalho Pinto"

  - trigger: ":eeah:"
    replace: "E.E. Alexandre Von Humboldt"

  - trigger: ":prp:"
    replace: "Programa de Residência Pedagógica (PRP)"

  - trigger: ":ecco:"
    replace: "Grupo de Pesquisa em Educação em Ciência e Complexidade (ECCo)"

  - trigger: ":fap:"
    replace: "Departamento de Física Aplicada (FAP)"

  - trigger: ":ldfull:"
    replace: "Laboratório de Demonstrações Ernst Wolfgang Hamburger"

  - trigger: ":ld:"
    replace: "Laboratório de Demonstrações"

  - trigger: ":ldsite:"
    replace: "http://labdemo.if.usp.br/"

    # Geral
  - trigger: ":abs:"
    replace: "Abraços,\n"

  - trigger: ":parabens:"
    replace: "Parabéns! LoL Feliz Aniversário! 🎉🎉 🙂"
